### ISSUE TITLE
idea中代码内容含双引号时无法send

### ISSUE THREAD

**Issue by Gyyyyyy6** [obiscr/ChatGPT#14]
正常聊天时键入双引号没有问题，不过代码中出现了就不能send，例如：
`System.out.println("ChatGPT");`

我的idea插件版本是1.0.1

**Comment by jiahuan-chen** [comment]
**The Same problem**
_这是VScode的插件_
![image](https://user-images.githubusercontent.com/83115039/206888206-0f10655a-155c-4e9d-ae86-21e76ad13154.png)
_这是IDEA的插件_
<img width="407" alt="b19e62415f92e730896c9cea7414b09" src="https://user-images.githubusercontent.com/83115039/206888142-10c40e94-3c17-4263-9115-b491d492246c.png">

**Comment by obiscr** [comment]
感谢反馈，我会处理的

**Comment by obiscr** [comment]
这居然是个fastjson的问题

**Comment by yufeng-liang** [comment]
我也遇到了同样的问题😭
