### ISSUE TITLE
升级了 2023.1 后， online chatGPT 输入响应有问题

### ISSUE THREAD

**Issue by Yixi** [obiscr/ChatGPT#166]
输入法只响应键盘字母输入
不响应回车换行，也不响应输入法

**Comment by obiscr** [comment]
感谢反馈，确实有此问题

**Comment by obiscr** [comment]
还没有的，这是ide的bug，可能需要等待ide修复。

**Comment by zjz2009000** [comment]
是的我也碰到了

**Comment by obiscr** [comment]
现在他是可以正常输入，不过光标确实是有问题的。

**Comment by obiscr** [comment]
About this bug, please see this thread: [Can not input chinese in jcef page under 2023.1 in macOS](https://youtrack.jetbrains.com/issue/IDEA-316584/Can-not-input-chinese-in-jcef-page-under-2023.1-in-macOS)

I tried it, but it's not working.

**Comment by obiscr** [comment]
It's will be fixed in 2023.2, more details please see: https://youtrack.jetbrains.com/issue/IDEA-316584/Can-not-input-chinese-in-jcef-page-under-2023.1-in-macOS#focus=Comments-27-7320120.0-0
