### ISSUE TITLE
Online ChatGPT does not use proxy settings

### ISSUE THREAD

**Issue by max4com** [obiscr/ChatGPT#170]
Online ChatGPT tab does not use proxy settings

**Comment by obiscr** [comment]
>In general, you do not need to configure a proxy for online chat GPT.

However, if it does not work, you can try to configure the proxy using the following step

Open: File - Settings/Preferences - Appearance and Behavior - System Settings - HTTP Proxy. And config proxy here.

**Comment by max4com** [comment]
> > In general, you do not need to configure a proxy for online chat GPT.
> 
> However, if it does not work, you can try to configure the proxy using the following step
> 
> Open: File - Settings/Preferences - Appearance and Behavior - System Settings - HTTP Proxy. And config proxy here.

Global proxy settings of course work. The problem is that proxy is needed exclusively for the work of ChatGPT

**Comment by awakelee** [comment]
Is there any news on this issue?

**Comment by obiscr** [comment]
Sorry for late, for some reasons, Online ChatGPT Tab will be deprecated in the future.
