### ISSUE TITLE
Can not go back when click link in online ChatGPT

### ISSUE THREAD

**Issue by thieucong98** [obiscr/ChatGPT#177]
Can not go back when click link in online ChatGPT #177

**Comment by obiscr** [comment]
![image](https://user-images.githubusercontent.com/28687074/230595417-d327fd48-b00a-4ef9-a425-0fd1a0daf39e.png)

Do you mean similar to the browser's return to the previous page?

**Comment by thieucong98** [comment]
![image](https://user-images.githubusercontent.com/46368852/230809413-6a7003ed-0166-4280-a7bf-cffc048b57f1.png)
I think your plugin adds this feature to the 'Online ChatGPT' tab. You can try clicking on the link shown in the image, or you can click on any link in the chatGPT results

**Comment by obiscr** [comment]
I will try to fix it.

**Comment by WKINGKING** [comment]
My problem is that I can't open Online ChatGpt,It's a Blank page. 大佬 我的问题是我点击Online ChatGpt如下图 所示：
![image](https://user-images.githubusercontent.com/75408611/233559621-269d4b69-78f3-4088-af17-cbd07c557ae8.png)

**Comment by obiscr** [comment]
If there is anything error log. It's shoule be network problem. Please try to change your ip address.

**Comment by obiscr** [comment]
This issue is out of date.
