### ISSUE TITLE
allow to configure custom openai deployment and model name

### ISSUE THREAD

**Issue by cforce** [obiscr/ChatGPT#190]
Existing openai libs work well with Azure Openai, you juts need to allow to configure a custom an Url additional to the existing options
The api will provide deployment name and model name. but your UI only offers one of it  - i assume implicit the drop-down is used for model name. I also tried to create deployment name wit the same name as model name but that did't work around it.

```
response = openai.Completion.create(
        prompt=full_prompt,
        temperature=0, 
        max_tokens=max_model_response_tokens,
        top_p=1,  # Similar to temperature, this controls randomness but uses a different method. Lowering Top P will
        frequency_penalty=0,
        presence_penalty=0,
        # presence_penalty is a value that penalizes the generation of words that are not present in
        model=COMPLETIONS_MODEL,  # text-davinci-003
        engine=COMPLETIONS_MODEL_DEPLOYMENT,  # DEPLOYMENT_NAME in Azure OpenAI for the model of type text-davinci-003
        stop=None
    )
```

**Comment by obiscr** [comment]
Thank for report, actually I am plan to support Azure.

**Comment by avolar133** [comment]
Any news regarding azure support?

**Comment by obiscr** [comment]
Not yet.There is a lot of work that needs to be done.

**Comment by obiscr** [comment]
Hi guys, for now, you can customize the model name and server here. Sorry for the late reply.

![image](https://github.com/obiscr/ChatGPT/assets/28687074/98859408-8990-444a-b0e7-f2fd3d507fa1)

This issue will be closed and opened again later if needed.
