### ISSUE TITLE
【feature】期望支持markdown语法

### ISSUE THREAD

**Issue by 0000005** [obiscr/ChatGPT#192]
期望支持markdown语法
![image](https://user-images.githubusercontent.com/9690089/232647354-ebb31e96-b441-43a4-a2f8-4d3fbf811ef0.png)

**Comment by obiscr** [comment]
感谢反馈，会尽快支持。

**Comment by obiscr** [comment]
markdown 语法现在已经支持。

**Comment by obiscr** [comment]
请升级到3.0.0版本
