### ISSUE TITLE
请问可以增加支持API2D的api吗？

### ISSUE THREAD

**Issue by Saunak626** [obiscr/ChatGPT#200]

**Comment by NiaoBlush** [comment]
同问

**Comment by anhao** [comment]
![image](https://github.com/obiscr/ChatGPT/assets/9844218/b7f95be5-4cb4-44aa-b141-7e1df7ba92f2)

设置对应的API和API地址就可以了

https://api.aigc2d.com/v1/chat/completions

**Comment by obiscr** [comment]
@anhao Thanks you very much!

**Comment by obiscr** [comment]
@anhao Thank you very much!

**Comment by NiaoBlush** [comment]
api2d按照楼上配置自定义服务器后, 提示:
![image](https://github.com/obiscr/ChatGPT/assets/15683067/1c8374f5-0ad9-4f02-94fd-60fe2a160027)

查询api2d错误码得知 参数中没有提供模型参数
![image](https://github.com/obiscr/ChatGPT/assets/15683067/50d6cd23-8e95-407c-b5d6-22661bcbf785)

**Comment by anhao** [comment]
> api2d按照楼上配置自定义服务器后, 提示: ![image](https://user-images.githubusercontent.com/15683067/269134839-1c8374f5-0ad9-4f02-94fd-60fe2a160027.png)
> 
> 查询api2d错误码得知 参数中没有提供模型参数 ![image](https://user-images.githubusercontent.com/15683067/269134978-50d6cd23-8e95-407c-b5d6-22661bcbf785.png)
> 
> 当前配置如下: ![image](https://user-images.githubusercontent.com/15683067/269136679-4cc27d4d-b2b5-4874-a79f-079776b60de5.png)

那就是这个平台的接口没做兼容，你可以试一下 AIGC2D

**Comment by NiaoBlush** [comment]
@anhao 试了下, AIGC2D可用
