### ISSUE TITLE
调用线程池关闭，但每次都新建了一个

### ISSUE THREAD

**Issue by wangwangxf** [obiscr/ChatGPT#206]
ChatGPTHandler 中使用了几处 mainPanel.getExecutorService().shutdown(); 但get 方法每次都new了一个

 public ExecutorService getExecutorService() {
        executorService = Executors.newFixedThreadPool(1);
        return executorService;
    }

**Comment by obiscr** [comment]
是的，每次用完以后就会关闭。下次在使用的时候会打开新的线程池。

**Comment by obiscr** [comment]
此问题在3.0.0已经修复。
