### ISSUE TITLE
代码显示优化，希望可以有专门的代码view

### ISSUE THREAD

**Issue by ipconfigall** [obiscr/ChatGPT#209]
目前返回的内容，没有做内容格式上的优化，比如说代码，阅读性比较差

**Comment by xindoo** [comment]
+1

**Comment by obiscr** [comment]
很抱歉耽搁了这么久，之前也有过类似的issue，经过我目前的测试，始终没有比较好的方式处理这个问题，不过我会继续更进。

**Comment by obiscr** [comment]
目前更新了一个版本，仅支持了高亮显示。
