### ISSUE TITLE
进度条一直处于加载状态 版本 2023.1

### ISSUE THREAD

**Issue by kanmomo318** [obiscr/ChatGPT#211]
<img width="412" alt="Snipaste_2023-04-28_20-28-17" src="https://user-images.githubusercontent.com/26961320/235147732-2e0793b2-49ab-40e7-bc4f-9134a441b1e7.png">

**Comment by obiscr** [comment]
应该是网络导致的。无法连接到服务器。可以适当设置（数值调小）连接超时。如果连接不到服务器，就断开连接。不继续等待。

**Comment by obiscr** [comment]
这个问题已经找到，它会在下个版本修复。

**Comment by obiscr** [comment]
这个问题已经修复，请更新到最新版本。
