### ISSUE TITLE
使用online chatgpt时登录openai用google登录显示不安全的浏览器无法登录

### ISSUE THREAD

**Issue by paststrange** [obiscr/ChatGPT#212]
pycharm版本2023.1.1

**Comment by obiscr** [comment]
根据目前的情况来看，部分用户会有这个情况，我个人的推测可能是跟ip地址有关系。

**Comment by paststrange** [comment]
> 根据目前的情况来看，部分用户会有这个情况，我个人的推测可能是跟ip地址有关系。

主要我在我的edge浏览器登录是正常的。

**Comment by obiscr** [comment]
可以尝试点击 X 清理一下cookie，然后重新刷新一下网页。看能否正常工作。

**Comment by paststrange** [comment]
> 可以尝试点击 X 清理一下cookie，然后重新刷新一下网页。看能否正常工作。

试过了，还是不行

**Comment by mingliao1994** [comment]
一样的问题，使用chrome登录没有问题，但是使用online chatgpt会提示This browser or app may not be secure.

**Comment by obiscr** [comment]
好的，非常感谢。现在是我这里无法复现这个问题。请问您是否设置了代理服务器？

**Comment by obiscr** [comment]
感谢各位之前的反馈，不过很抱歉的是，这个feature会再下个版本被弃用。因此目前暂时不打算修复了。
