### ISSUE TITLE
在pycharm新ui中找不到

### ISSUE THREAD

**Issue by paststrange** [obiscr/ChatGPT#222]
pycharm版本2023.1.1
经典ui在右侧可以找到，新ui右侧不显示

**Comment by obiscr** [comment]
您好，请问能否提供一下插件版本以及PyCharm的版本，如果可以的话，最好附带一下 pycharm的log。

**Comment by paststrange** [comment]
PyCharm 2023.1.1 (Professional Edition)
Build #PY-231.8770.66, built on April 28, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.zh (231.283)
    leetcode-helper (1.7.0)
    CMD Support (1.0.5)
    ChatGPT (2.2.1-222.231)
    izhangzhihao.rainbow.brackets (2023.2.7)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-231)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.0)
[pycharm-logs-20230512-22384510192434692571798089.zip](https://github.com/dromara/ChatGPT/files/11465234/pycharm-logs-20230512-22384510192434692571798089.zip)

**Comment by obiscr** [comment]
抱歉回复晚了，请问能否尝试重新安装一下？

**Comment by paststrange** [comment]
> 抱歉回复晚了，请问能否尝试重新安装一下？

今天刚更新了插件，还是显示不出来

**Comment by obiscr** [comment]
之前的日志我看了，没发现什么明显的问题。请问插件是否启用了？

**Comment by obiscr** [comment]
此问题已经过时，会暂时关闭。另外近期更新了3.0.0版本，有重大的更新。可以尝试3.0.0版本是否工作正常。
