### ISSUE TITLE
关于线程池shutdown的bug

### ISSUE THREAD

**Issue by Li17860397285** [obiscr/ChatGPT#223]
ChatGPTHandler和GPT35TurboHandler中执行mainPanel.getExecutorService().shutdown()时getExecutorService方法应该获取之前创建的线程池，但是当前代码是创建了一个新的线程池

**Comment by obiscr** [comment]
是的，因为发送操作并不是很频繁，在这个项目里面不涉及并发，一次操作至少也需要500ms吧，平均来讲。因此就关闭了。

shutdown 之后不能再次使用了。只能重新开启新的线程池。

**Comment by obiscr** [comment]
是的，因为发送操作并不是很频繁，在这个项目里面不涉及并发，一次操作至少也需要500ms吧，平均来讲。因此就关闭了。

shutdown 之后不能再次使用了。只能重新开启新的线程池。

**Comment by Li17860397285** [comment]
> 是的，因为发送操作并不是很频繁，在这个项目里面不涉及并发，一次操作至少也需要500ms吧，平均来讲。因此就关闭了。
> 
> shutdown 之后不能再次使用了。只能重新开启新的线程池。

我懂你的意思，但是我的意思是，执行mainPanel.getExecutorService().shutdown()应该是关闭之前创建的线程池，但是现在的代码是创建一个新的线程池然后紧接着关闭了。

**Comment by obiscr** [comment]
非常感谢，我明白你的意思了，你指的应该是在 `onEvent` 事件中，不应该 shutdown()，是吧？

**Comment by obiscr** [comment]
这个问题在3.0.0版本已经修复。感谢反馈！
