### ISSUE TITLE
custom prompt消失

### ISSUE THREAD

**Issue by liuyueheng** [obiscr/ChatGPT#225]
每次一更新后，custom prompt保存的自定义内容就消失了

**Comment by obiscr** [comment]
感谢反馈，之前也有人提到过这个问题，但是我始终无法复现。我会继续尝试。

**Comment by liuyueheng** [comment]
好的 加油 期待你们修复

**Comment by obiscr** [comment]
这个问题应该不会出现了，请尝试更新到3.0.0版本，看是否还会有此问题。
