### ISSUE TITLE
好像现在登录有些问题

### ISSUE THREAD

**Issue by guolovesong** [obiscr/ChatGPT#226]
![5cd1ae2719e25e58dcedafc49149582](https://github.com/dromara/ChatGPT/assets/63273298/e6c6167f-c53d-4a95-8109-8d1966a11f21)
![e50abebd49bb805581b4cae03450486](https://github.com/dromara/ChatGPT/assets/63273298/e57d6bb5-c1f9-4a2a-9c07-2e3caed16c95)

**Comment by obiscr** [comment]
根据我的测试，则应该是OpenAI官方导致的。如果出现这种情况，那么你在浏览器，也是需要重新登录才可以。重新获取token就好啦。
