### ISSUE TITLE
Insert Code / Replace Selection

### ISSUE THREAD

**Issue by JasonEleventeen** [obiscr/ChatGPT#230]
Can we have a button added to replace or insert code at cursor (if no selection) from the chatgpt answer instead of just copy

**Comment by obiscr** [comment]
Thanks, That's a good suggestion. I will support it as soon as possible.

**Comment by obiscr** [comment]
Hi, In 3.0.0 version, we supportd the code highlight, and support to insert to code to editor. Thanks.
