### ISSUE TITLE
Your authentication token has expired - but thats not true

### ISSUE THREAD

**Issue by jmartsch** [obiscr/ChatGPT#231]
When using "ChatGPT" with model 4 I get the following error when making a request:
`Response failure, please try again. Error message: {"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}}`

I renewed my authentication token and in the settings of the plugin the expiration date is in the future
![image](https://github.com/obiscr/ChatGPT/assets/551551/0d00f9c5-eeb1-4401-aa04-cf076f5c7cb2)

how can i fix this?

**Comment by obiscr** [comment]
Hi, this is duplicate with #226 

According to my test, then it should be officially caused by OpenAI. If this happens, then you need to log in again in your browser, too. Just get the token again.

**Comment by obiscr** [comment]
Sorry for late, yeah, You have been re-loggin the website in browser. It's **Step1**, and the next step, you only need to open [session url](https://chat.openai.com/api/auth/session), copy the access token to plugin settings. It shoule be working.
