### ISSUE TITLE
Response failure, please try again. Error message: {"detail":{"message":"Could not parse your authentication token. Please try signing in again.","type":"invalid_request_error","param":null,"code":"invalid

### ISSUE THREAD

**Issue by angelbaba** [obiscr/ChatGPT#233]
大佬,请问下,这个是什么原因,同样的token台式机可以用,笔记本换了几个账号的token都不行,报这个错误Response failure, please try again. Error message: {"detail":{"message":"Could not parse your authentication token. Please try signing in again.","type":"invalid_request_error","param":null,"code":"invalid
![image](https://github.com/obiscr/ChatGPT/assets/45415907/4b80b3eb-2251-4ce0-8815-cdfddea2e41e)

**Comment by obiscr** [comment]
抱歉回复晚了，请问这是那个Tab出现的？

**Comment by obiscr** [comment]
目前已经更新了 3.0.0版本，请尝试3.0.0版本是否还有此问题，非常感谢！
