### ISSUE TITLE
Can not login using Google sign in method in Rider

### ISSUE THREAD

**Issue by Tsadriu** [obiscr/ChatGPT#235]
How to reproduce:

- Go to the Online ChatGPT tab in Rider.
- Select "Sign in with Google".
- Input your email and press **Next**.
- The message This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can try again to sign in." will appear.

**Comment by obiscr** [comment]
Sorry for late, I tried three computer, it all working fine. I think this may be due to network problems.

**Comment by obiscr** [comment]
This issue is out of date.
