### ISSUE TITLE
End of life for gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by InstaZDLL** [obiscr/ChatGPT#236]
gpt-3.5-turbo-0613 has been released and now there is version gpt-3.5-turbo-16k can you add these two versions and delete the old gpt-3.5-turbo-0301?

### Old :
- gpt-3.5-turbo-0301

### New :
- gpt-3.5-turbo-0613
- gpt-3.5-turbo-16k
- gpt-3.5-turbo-16k-0613

https://platform.openai.com/docs/models/gpt-3-5

**Comment by obiscr** [comment]
Thanks, the latest model will be support in next version.

**Comment by obiscr** [comment]
Hi, Please update to 3.0.0 version, the latest models has been supported.
