### ISSUE TITLE
Add Monospace Font and Code Highlighting for Code Output

### ISSUE THREAD

**Issue by kunieone** [obiscr/ChatGPT#237]
Dear obiscr,

    I hope this message finds you well. First and foremost, I would like to express my gratitude for the incredible work you have done in developing the built-in ChatGPT within Android Studio. It has been an invaluable tool for me, and I truly appreciate the effort you have put into its development.
    I am writing today to suggest an enhancement that I believe would greatly improve the code output experience. Currently, when the ChatGPT returns code snippets, it would be fantastic if the text was displayed in a monospace font and accompanied by code highlighting. These additions would significantly enhance the readability and comprehension of the returned code.
By utilizing a monospace font, such as Courier or Consolas, the alignment and spacing of the code would be consistent, making it easier to distinguish between different elements. Furthermore, incorporating code highlighting, with different colors or styles for keywords, variables, and comments, would provide visual cues that aid in understanding the code's structure and syntax.
    I understand that implementing such features may require some adjustments to the rendering of the code output. However, I believe that the benefits in terms of code readability and user experience would be substantial.
Once again, thank you for your hard work and dedication in creating this invaluable tool for developers. I sincerely hope you consider my suggestion, as I believe it would greatly enhance the overall experience of using ChatGPT within Android Studio.
If there is anything I can do to support or contribute to this project, please do not hesitate to let me know. I look forward to seeing the continued development of this remarkable tool.

Thank you and best regards.

**Comment by obiscr** [comment]
Thanks, it will be support in the next version. And it comming soon.

**Comment by obiscr** [comment]
Hi, @kunieone Please update to 3.0.0 version, code highlight has been supported.
