### ISSUE TITLE
在使用 Online ChatGPT时，复制功能无法使用。

### ISSUE THREAD

**Issue by ByteDanceZhao** [obiscr/ChatGPT#238]
2.2.5-203.221 无法复制到剪贴板。其实一直有这个问题。

**Comment by obiscr** [comment]
感谢反馈。不过很抱歉的是，这个feature会再下个版本被弃用。因此目前暂时不打算修复了。

**Comment by ByteDanceZhao** [comment]
您好，非常感谢您的工具，它非常好用。

**Comment by ByteDanceZhao** [comment]
你好，非常感谢您的工具，它非常好用。但我本人更喜欢使用在线版。我想请问一下，我在您插件的Online ChatGPT页面使用在线版时，能够正常登录和使用。但在chrome使用在线版chatGPT时，会提示Sorry, you have been blocked。我们公司的网络能够正常访问Google，IP地址位于Hong Kong。

**Comment by obiscr** [comment]
> Sorry, you have been blocked

根据用户反馈的情况，这个错误基本上99%是因为IP问题导致。因此要想解决还是需要您尝试更换其他的IP地址。
