### ISSUE TITLE
The ChatGPT Tab and Online ChatGPT Tab mark as Deprecated

### ISSUE THREAD

**Issue by obiscr** [obiscr/ChatGPT#240]
# Important

The ChatGPT Tab and Online ChatGPT Tab will be removed in the next release. Please use the “EasyCode” tab instead.

**Comment by prime-zs** [comment]
Please dont depricate them, these were fast; the new EasyCode is slow and produces wrong output. It sometimes mixes contexts

**Comment by mo2menelzeiny** [comment]
First great work on the plugin, it's very useful.

If you're going to deprecate them, are you going to provide a way for Subscribed ChatGPT users to access their accounts using token, because that is very important as it makes you leverage your existing subscription.

Thanks

**Comment by obiscr** [comment]
Thank you for your suggestions. We will carefully consider it and the latest version 3.0.1 has not been removed yet. Can be updated to the latest version.

**Comment by controlado** [comment]
I didn't need to come to comment but I would like to say that I love being able to use the token to log in, thank you very much!

**Comment by obiscr** [comment]
Hi, this issue will be closed. Please see #307 for more information. Thank you :D!
