### ISSUE TITLE
incorrect API key (looks as if it's cached)

### ISSUE THREAD

**Issue by fredzannarbor** [obiscr/ChatGPT#241]
Hi, 

on GPT-3.5-Turbo tab I'm getting this:

"Incorrect API Key received".

However, the key echoed back is an old one that is not the one I have set in Settings.  I opened/closed, activated/deactivated plugin, installed/reinstalled plugin, still getting this error message.

**Comment by obiscr** [comment]
Hi, thanks, can you provide the plugin version and ide version?

**Comment by fredzannarbor** [comment]
Build #PY-231.9161.41, built on June 20, 2023
3.0.0-231

**Comment by obiscr** [comment]
Sorry that I did not reproduce the problem.

Can you try with follow steps:
1. Open GPT-3.5-Turbo settings.
2. Delete the API Key and click Apply -> Ok.
3. Open the settings again, refill the API Key, click Apply -> Ok

Then check if it will work properly.

**Comment by fredzannarbor** [comment]
Fixed it.
