### ISSUE TITLE
EasyCode不能回答

### ISSUE THREAD

**Issue by liuyiya** [obiscr/ChatGPT#242]
Waiting for response...

![微信截图_20230626132846](https://github.com/obiscr/ChatGPT/assets/49060368/13b479cb-f9c1-4894-ba75-abff8cbd4f52)
![微信截图_20230626132924](https://github.com/obiscr/ChatGPT/assets/49060368/1454e693-2680-4a88-a3cc-c92b8cf09ea1)

**Comment by obiscr** [comment]
能否发送 `idea.log` 到我的邮箱：wuzi@obiscr.com?
点击菜单栏的 **Help** - **Show log in Explorer**, 然后可以找到 `idea.log`

**Comment by liuyiya** [comment]
发送过了

**Comment by obiscr** [comment]
根据日志结果，这是您的网络问题，无法连接到服务器导致。

**Comment by obiscr** [comment]
根据查询结果，这是您的网络问题，无法连接到服务器导致。

**Comment by yesgit** [comment]
easycode的服务器地址是？
