### ISSUE TITLE
点击侧边栏的ChatGPT导致IDEA崩溃

### ISSUE THREAD

**Issue by DarkGhast** [obiscr/ChatGPT#243]
IDEA版本 2022.2，点击侧边栏尝试打开插件时，IDEA闪退
![image](https://github.com/obiscr/ChatGPT/assets/44697474/445e0699-0858-4f82-8617-a7d3bded772d)
idea.log由于直接闪退没有日志，以下是重启后IDEA提供的错误信息
[crash.txt](https://github.com/obiscr/ChatGPT/files/11879904/crash.txt)

**Comment by obiscr** [comment]
这个问题应该是IDE本身的BUG

**Comment by obiscr** [comment]
现在是每次都会出现吗?

**Comment by DarkGhast** [comment]
是的，点击、右键以及通过视图-工具窗口尝试打开都会出问题，其他插件（如Redis）没出现这种情况

**Comment by obiscr** [comment]
好的，上一个版本是2.2.5，目前最新版是3.0.0. 但是在3.0.0中，没有修改任何Online ChatGPT 相关的东西（这个问题就是Online ChatGPT 引发的）。

作为临时的解决方案：建议您先使用上一个2.2.5的版本，可以在这里下载：https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode/versions/stable/343432

Online ChatGPT回来未来的版本中移除。等新版本更新了，您可以更新到最新版。
