### ISSUE TITLE
只保留一个tab时隐藏左侧会话框无效

### ISSUE THREAD

**Issue by CialloAlone** [obiscr/ChatGPT#244]
![image](https://github.com/obiscr/ChatGPT/assets/49114142/214ac476-9b0b-41a3-89b9-1a84b18d6a11)

**Comment by obiscr** [comment]
请在ToolWindow Setting 中把保留的这一个Tab放到第一位，重启之后，隐藏对话应该会生效
![image](https://github.com/obiscr/ChatGPT/assets/28687074/95d8cf7f-744f-4702-b7c9-e9886f6223e3)
