### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by levitastech** [obiscr/ChatGPT#247]
Hi

I would like to post a suggestion to implement a new feature 

It will be great if you add the possibility to use local hosted model like Gpt4All instead of the openai chatGpt.

Thank you for your efforts.
Regards

**Comment by obiscr** [comment]
Thank you for your suggestion. It sounds great and we will consider adding it in future versions.

**Comment by obiscr** [comment]
Unfortunately, after a final decision, we are not going to support gpt4all in extensions for the time being. Thanks for the suggestion.
