### ISSUE TITLE
Plugin does not work at all

### ISSUE THREAD

**Issue by oVerde** [obiscr/ChatGPT#249]
![Screencast from 2023-07-05 11-35-43](https://github.com/obiscr/ChatGPT/assets/1839750/30b5dc89-85b8-4acf-9e1b-914cc68d7281)

![image](https://github.com/obiscr/ChatGPT/assets/1839750/40b19ecc-6ed2-47e5-8cde-dbac9576000f)

WebStorm 2023.1.3
Build #WS-231.9161.29, built on June 15, 2023
Licensed to Danilo Verde
Subscription is active until October 10, 2023.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.3.10-200.fsync.fc37.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 1934M
Cores: 16
Registry:
    editor.focus.mode.color.light=5b595c
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    editor.distraction.free.mode=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=5b595c
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    io.unthrottled.amii (1.1.7)
    com.intellij.ideolog (222.1.0.0)
    com.github.copilot (1.2.9.2684)
    lermitage.intellij.extratci (1.26.0)
    Key Promoter X (2023.1.0)
    com.tabnine.TabNine (1.0.24)
    ChatGPT (3.0.1-231)
    com.github.shiraji.emoji (3.1.0)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    com.pixelperfect.npm-package-json (2023.0.3)
    some.awesome (1.14)
    org.jetbrains.search-everywhere-docs (1.0.12)
    awesome.console (0.1337.12)
    com.samvtran.plugins.macosforallkeymap (2.0.0)
    ru.adelf.idea.dotenv (2023.1)
    com.chylex.intellij.inspectionlens (1.3.0)
    monokai-pro (1.10)
    izhangzhihao.rainbow.brackets (2023.2.11)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
    com.haulmont.rcb (2023.2.4-231)
    com.intellij.lang.jsgraphql (4.0.1)
    com.intellij.react.css.modules (1.0.1)
    com.mallowigi (90.0.0)
    uk.co.ben-gibson.remote.repository.mapper (4.3.3)
    zielu.gittoolbox (500.0.13+213)
    mobi.hsz.idea.gitignore (4.5.1)
    org.sonarlint.idea (8.4.0.73538)
    commit-template-idea-plugin (1.2.0)

Current Desktop: GNOME

![image](https://github.com/obiscr/ChatGPT/assets/1839750/82aefd0e-125f-460a-b12e-208a6106dc41)

**Comment by obiscr** [comment]
Hi, could you send the `idea.log` to wuzi@obiscr.com? thanks.

**Comment by oVerde** [comment]
Sent

**Comment by obiscr** [comment]
It looks like something went wrong, I haven't received an email yet.

**Comment by oVerde** [comment]
resent

**Comment by obiscr** [comment]
Thanks @oVerde, I found the problem on this side because of your network problem. Unable to access the server caused.

**Comment by oVerde** [comment]
Well, will we have an update to prevent the looping infinite scrolling?

**Comment by obiscr** [comment]
Currently, the component will always keep scrolling to the bottom while the content is being generated, and the scrollbar is free to scroll after the generation is complete.

**Comment by oVerde** [comment]
> Currently, the component will always keep scrolling to the bottom while the content is being generated, and the scrollbar is free to scroll after the generation is complete.

This is not the case, I can open past chat and the window will endlessly loop into scrolling, causing my fans to heat up.
When some fix appears, I shall re-install.

**Comment by obiscr** [comment]
This looks like it could be an IDE bug. i will try to reproduce it again. Thanks.

**Comment by szymski** [comment]
Bump. I wanted to try this plugin so badly, but the same problem stops me from doing anything with it. My IDE is Rider.
```
JetBrains Rider 2023.2 EAP 10
Build #RD-232.8660.134, built on July 20, 2023
Licensed to JetBrains Rider EAP user: Szymon Jankowski
Expiration date: August 19, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v7.0.7 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    search.everywhere.settings=true
    ide.experimental.ui=true
    ide.new.project.model.index.case.sensitivity=true
    vcs.empty.toolwindow.show=false
    database.show.search.tab=false

Non-Bundled Plugins:
    cognitivecomplexity-rider (2023.2.0-eap06)
    org.jetbrains.advocates.rider.plugins.dotnetwatch (2023.2.2)
    it.czerwinski.intellij.wavefront (1.4.2)
    com.jetbrains.rider.android (232.8660.134)
    de.netnexus.camelcaseplugin (3.0.12)
    com.intellij.resharper.HeapAllocationsViewer (2023.2.0-eap06)
    org.yh.statistics.plugin (1.0.1)
    org.yapal.world.commandlinelauncher (2.1.0)
    com.thvardhan.gradianto (5.3)
    fluentvalidation-rider (2023.2.0-eap03)
    de.femtopedia.diffplugin (2.1.11)
    Unicode Browser (0.8.1-15.0)
    com.samdark.intellij-visual-studio-code-dark-plus (2.7)
    com.vecheslav.darculaSolidTheme (1.0.3)
    org.toml.lang (232.8660.88)
    indent-rainbow.indent-rainbow (2.1.0)
    com.mirkoalicastro.gotogit (0.0.3)
    GrepConsole (12.18.211.6693.0)
    ee.carlrobert.chatgpt (2.0.5)
    dev.patrickpichler.darculaPitchBlackTheme (1.0.0)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    com.intellij.javafx (1.0.4)
    com.guohanlin.JsonToAnyLanguage (2023.1.6)
    ca.nosuchcompany.rider.plugins.mediatr (23.06.0210)
    idea.plugin.protoeditor (232.8660.88)
    com.github.bufbuild.intellij (0.1.4)
    com.github.blarc.ai-commits-intellij-plugin (1.2.1)
    zielu.gittoolbox (500.0.13+213)
    uk.co.ben-gibson.remote.repository.mapper (4.3.5)
    Statistic (4.2.7)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    com.intellij.grpc (232.8660.88)
    com.github.lppedd.idea-conventional-commit (0.22.0)
    String Manipulation (9.9.0)
    com.intellij.resharper.StructuredLogging (2023.2.0.301-eap09)
    github.cweijan.test-theme (1.6)
    com.intellij.apacheConfig (232.8660.88)
    org.wavescale.sourcesync (3.0.2)
    krasa.CpuUsageIndicator (1.15)
    com.hiberbee.intellij.hiberbee-theme (2023.5.19.1923)
    ru.adelf.idea.dotenv (2023.2)
    space.vistarsvo.embrowser (1.1.3)
    club.nutsoft.Github3Theme (1.2.0)
    com.dsoftware.ghtoolbar (1.13.1)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    com.github.codespaces.jetbrains.gateway (0.5.0.1214)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    co.anbora.labs.ngrok (1.3.9)
    com.github.camork.fileExpander (2.1)
    com.github.dinbtechit.vscodetheme (1.8.5)
    io.jetclient (2023.1.14-232)
    mdx.js (232.8660.129)
    com.intellij.lang.jsgraphql (4.0.1)
    izhangzhihao.rainbow.brackets.lite (1.0.1)
    org.exbin.deltahex.intellij (0.2.8.1)
    me.seclerp.rider.plugins.efcore (232.0.0-eap07)
    com.intellij.bigdatatools.core (232.8660.142)
    com.intellij.bigdatatools.binary.files (232.8660.142)
    com.intellij.bigdatatools.rfs (232.8660.142)
    com.mallowigi.colorHighlighter (15.0.0)
    name.kropp.intellij.makefile (232.8660.88)
    com.karateca.jstoolbox (1.10)
    com.github.copilot (1.2.15.2816)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
```

**Comment by obiscr** [comment]
Thanks, I will test it at Rider.

**Comment by obiscr** [comment]
@szymski I use the Rider with same version, It's working fine on my side.
Can you upgrade to latest version 3.0.4 try if it is normally.

**Comment by zl03jsj** [comment]
i got the same question on  mac os, this is my idea information:
```
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 13, 2023
Licensed to 
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    editor.minimap.enabled=true
    go.run.processes.with.pty=false

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.9921.89)
    Batch Scripts Support (1.0.13)
    name.kropp.intellij.makefile (232.8660.88)
    org.jetbrains.plugins.go (232.9921.28)
    me.lensvol.blackconnect (0.6.1)
    com.intellij.plugins.watcher (232.8660.88)
    org.rust.lang (0.4.201.5424-232)
    org.jetbrains.plugins.ruby (232.9921.47)
    org.jetbrains.plugins.go-template (232.9921.89)
    com.intellij.ideolog (222.1.0.0)
    CMD Support (1.0.5)
    AceJump (3.8.16)
    IdeaVIM (2.6.3)
    org.jetbrains.IdeaVim-EasyMotion (1.10)
    com.intellij.spring.websocket (232.8660.142)
    au.com.glassechidna.luanalysis (1.4.0)
    ChatGPT (3.1.5-231.232)
    com.intellij.aqua (232.9921.28)
    PlantUML integration (7.3.0-IJ2023.2)
    com.kn.diagrams.generator.generator (2022.2.0)
    de.docksnet.puml.syntaxchecker (0.2.0)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    GrepConsole (12.22.1-IJ2021.1)
    me.serce.solidity (2.4.2)
    Pythonid (232.9921.47)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.intellij.bigdatatools.core (232.9921.47)
    com.intellij.bigdatatools.kafka (232.9921.47)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.9921.47)
    com.intellij.bigdatatools.metastore.core (232.9921.47)
    com.intellij.bigdatatools.flink (232.9559.34)
    com.intellij.bigdatatools.spark (232.9559.62)
    com.intellij.bigdatatools.zeppelin (232.8660.206)
    com.intellij.bigdatatools (232.9559.34)
    wl-spring-assistant (1.4.6.222.232)
    com.jetbrains.php (232.9921.55)

Kotlin: 232-1.9.0-IJ9921.47
```

**Comment by obiscr** [comment]
Hi, could you share your idea.log with me via wuzi@obiscr.com?

**Comment by zl03jsj** [comment]
> Hi, could you share your idea.log with me via [wuzi@obiscr.com](mailto:wuzi@obiscr.com)?

already sent to you

**Comment by obiscr** [comment]
@zl03jsj I'm sorry for replying so late. There is a lot of work that needs to be done.
Okay, when I check the history of my email records, I can't seem to find the email you sent me. Can you try updating to the latest version and see if you still have the problem?

**Comment by obiscr** [comment]
This issue is out of date and will be closed. And please update to latest version 3.3.1.
