### ISSUE TITLE
窗口里什么也没有 

### ISSUE THREAD

**Issue by zhouyanbl** [obiscr/ChatGPT#25]
![image](https://user-images.githubusercontent.com/13973761/206951444-a71ebac4-1b78-4197-8a1a-b0888ddfb309.png)
![image](https://user-images.githubusercontent.com/13973761/206951560-7f18cf23-ff35-4662-9e88-92054ffb3a87.png)
我用的最新版的Goland 也许是没兼容？

**Comment by zhouyanbl** [comment]
在IDEA没有这个问题

**Comment by obiscr** [comment]
请用最新的版本哦,尝试一下：https://plugins.jetbrains.com/files/20603/264795/ChatGPT-1.0.5.zip

**Comment by zhouyanbl** [comment]
可以了 谢谢
