### ISSUE TITLE
如何重置插件的设置

### ISSUE THREAD

**Issue by LightToDo** [obiscr/ChatGPT#257]
你好，请问能够重置设置吗？尝试卸载重新安装也不行。

**Comment by obiscr** [comment]
Hi, It's depends on you system.

| System | File Path |
|:--|:--|
| Linux | `~/.local/share/JetBrains/<product><version>/options/ChatGPTSettingsPlugin.xml` |
| macOS | `~/Library/Application Support/JetBrains/<product><version>/options/ChatGPTSettingsPlugin.xml` |
| Windows | `%APPDATA%\JetBrains\<product><version>\options\ChatGPTSettingsPlugin.xml` |

> Replace `<product><version>` on paths with your actual IDE Name.

Delete file `ChatGPTSettingsPlugin.xml` and restart the IDE.
