### ISSUE TITLE
点击按钮无反应。应该不是网络问题，我是美国的梯子，且能正常访问它的官网。token也设置了

### ISSUE THREAD

**Issue by LeoCao0707** [obiscr/ChatGPT#26]
![2022-12-12_11-29](https://user-images.githubusercontent.com/37643156/206954587-73c54cdd-0cda-459f-9409-52a45dbab346.png)
![2022-12-12_11-30](https://user-images.githubusercontent.com/37643156/206954635-ab6a71b6-7bbc-4ec7-94a9-febf383d07f2.png)

**Comment by happinessandlove** [comment]
我的现象和你一样的

**Comment by obiscr** [comment]
官方目前加了保护，屏蔽到了API访问，目前只能浏览器访问。正在想办法解决。

**Comment by Hecbi** [comment]
刚刚下载了插件，发现了相同的问题，等待作者的解决方法

**Comment by project4linwang** [comment]
同样的问题

**Comment by obiscr** [comment]
颇为无奈，好多API访问直接瘫痪了

**Comment by obiscr** [comment]
请看这边：[https://github.com/obiscr/ChatGPT/issues/28#issuecomment-1347819779](https://github.com/obiscr/ChatGPT/issues/28#issuecomment-1347819779)
