### ISSUE TITLE
Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null

### ISSUE THREAD

**Issue by JingwenLi** [obiscr/ChatGPT#260]
![image](https://github.com/obiscr/ChatGPT/assets/20828375/7c15354d-e058-479e-b927-c5789340f5db)

**Comment by geleonardo** [comment]
![image](https://github.com/obiscr/ChatGPT/assets/15099498/8318ca8a-1ee5-47f6-bbc1-cba5558fa282)

**Comment by chenlei0427** [comment]
![image](https://github.com/obiscr/ChatGPT/assets/26614095/3e59259d-33aa-47a9-a8d2-b28ee6ba1dd0)
只有问了下一个问题上一个问题的回答才能正常显示否则会出现截图的报错

**Comment by obiscr** [comment]
Thank you all, it's because of the  server response. And it will be fix as soon as possiable.

**Comment by mo2menelzeiny** [comment]
I'm getting the same on ChatGPT for Intellij Plugin on IDEA Ultimate

![image](https://github.com/obiscr/ChatGPT/assets/22756089/bee4bd51-cc46-41dc-bda4-bb27e8da2357)

**Comment by obiscr** [comment]
Yes, it will be fixed in version [3.0.4](https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode/versions/stable/366399). The new version is currently under review.

**Comment by obiscr** [comment]
The 3.0.4 version has been released, please upgrade to 3.0.4.

**Comment by obiscr** [comment]
Hi all, can anyone tell me if this problem has been fixed. On your machine? thanks.

**Comment by 15727684438** [comment]
> Hi all, can anyone tell me if this problem has been fixed. On your machine? thanks.

yes,it has been repaired
tks

**Comment by obiscr** [comment]
Got it, thank you!
