### ISSUE TITLE
Unchecking "Use tab character" not working

### ISSUE THREAD

**Issue by fpinnahub** [obiscr/ChatGPT#261]
I replicate here what I previously posted to [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/12561522895122-Unchecking-Use-tab-character-not-working?page=1#community_comment_12604349503378) PyCharm support page:

> Since I updated to release PyCharm 2023.1.4 (Community Edition), when I press tab I get "/t" and no more 4 spaces, even if in my settings -> editor -> code style -> python I left unchecked "Use tab character".
> 
> I also notice that in the example window inside the settings everything works correctly, unfortunately not while typing in actual files.

It resulted in an issue related to this plugin.

**Comment by obiscr** [comment]
Thank you @fpinnahub , yeah, I got the user feedback a few days ago. Please refer [this issue](https://github.com/obiscr/ChatGPT/issues/258#issuecomment-1637629883) for temporary site solutions.

**Comment by obiscr** [comment]
Also, this issue is duplicate with https://github.com/obiscr/ChatGPT/issues/258, stay tuned to #258 for follow up, thank you!
