### ISSUE TITLE
Other Settings/Model 怎么选择

### ISSUE THREAD

**Issue by vv0823** [obiscr/ChatGPT#262]
Gpt-3.5-turbo、gpt-3.5-turbo-16k。。。。。gpt-4 等等 这些要怎么选，怎么判断自己的可以用哪个
Response failure, please try again. Error message: {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
 "The model: `gpt-4-32k` does not exist", "type": "invalid_request_error", "param":

**Comment by obiscr** [comment]
如果您的账号，已经通过gpt-4的白名单审核，那么您可以使用gpt-4* 的model。否则请使用 
![image](https://github.com/obiscr/ChatGPT/assets/28687074/81396147-2911-4878-92fb-b6f1817cf731)

这是目前最新的模型。
