### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by zhaobinsir** [obiscr/ChatGPT#265]
复现步骤：向chatGpt提任意问题、当即将答复完成时 大概率会报如下错误
 Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null

**Comment by obiscr** [comment]
这个issue和 #260 重复，在最新的3.0.4版本已经修复，请更新到3.0.4版本。
