### ISSUE TITLE
EasyCode Tab "Waiting for response..."

### ISSUE THREAD

**Issue by obiscr** [obiscr/ChatGPT#267]
![image](https://github.com/obiscr/ChatGPT/assets/28687074/50cf7baa-c74f-497e-8a21-56cfcfa14d48)

We're having some server issues and can't answer.It is currently being fixed.

**Comment by kkezhong** [comment]
我也遇到同样的问题,idea版本是2023.2,不知道是不是插件目前不支持当前的idea版本

**Comment by obiscr** [comment]
请尝试更新到最新的3.1.0版本

**Comment by kkezhong** [comment]
![image](https://github.com/obiscr/ChatGPT/assets/117790580/f953f1b6-d1a8-4c7d-a8cc-31e9f1c86c31)
已经是最新的3.1.0版本了,但还是不行,无论是开了proxy还没开,proxy是香港的节点

**Comment by obiscr** [comment]
After uninstalling version 3.1.0, please restart the IDE and reinstall it.

**Comment by obiscr** [comment]
> ![image](https://user-images.githubusercontent.com/117790580/258288928-f953f1b6-d1a8-4c7d-a8cc-31e9f1c86c31.png) 已经是最新的3.1.0版本了,但还是不行,无论是开了proxy还没开,proxy是香港的节点

请卸载3.1.0版本以后，重新启动IDE之后重新安装即可。

**Comment by obiscr** [comment]
> ![image](https://user-images.githubusercontent.com/117790580/258288928-f953f1b6-d1a8-4c7d-a8cc-31e9f1c86c31.png) 已经是最新的3.1.0版本了,但还是不行,无论是开了proxy还没开,proxy是香港的节点

请卸载3.1.0版本以后，重新启动IDE之后重新安装即可。

**Comment by phpluo** [comment]
编辑器本身的TAB键补全 会被占用，禁用插件 Tab补全就是正常的 
The editor's own TAB key completion will be occupied, disable the plug-in Tab Completion is normal.
版本PhpStorm2023.2.3

**Comment by obiscr** [comment]
@phpluo 请问能否提供完整的复现方法。（相关的文件，或者IDE版本信息等等...）

**Comment by obiscr** [comment]
之前收到过类似的反馈，看起来是和Codeium有冲突，可以参考这里的 https://chatgpt.gold/zh/blog/posts/2023/Inline-autocomplete-is-now-supported/ 设置（最后一张图片）来禁用这个特性。

**Comment by EvanHong99** [comment]
感觉这个hotkey不是很合理，平时哪怕只是想tab/shift tab去indent都不行了，能否默认设置就避开一些常用快捷键呢？

**Comment by obiscr** [comment]
@EvanHong99 暂时请先使用 https://github.com/obiscr/ChatGPT/issues/267#issuecomment-1670627514 这里提到的方法先禁用。后期可能会调整一下。谢谢！
