### ISSUE TITLE
Response failure, cause: No route to host, please try again.

### ISSUE THREAD

**Issue by istoez** [obiscr/ChatGPT#268]
在GPT-3.5-Turbo标签下不管输入什么都提示
Response failure, cause: No route to host, please try again.

OpenAI的apikey和GPT-3.5-Turbo的apikey都配置了

**Comment by obiscr** [comment]
感谢反馈，我会进行测试。

**Comment by obiscr** [comment]
经过我的测试，应该是您网络的问题。我测试了几台设备，都工作正常。
