### ISSUE TITLE
There are errors in the generated code regarding sign conversion.

### ISSUE THREAD

**Issue by Chenjiangwen** [obiscr/ChatGPT#269]
In the code generated by chatGPT, using copy or insert to editor, the symbols: >, <, and '  ' will be converted to  & gt;'   '& lt;'  '& quot;' in  the editor.

**Comment by Chenjiangwen** [comment]
example:
the code generated by chatGPT:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n-1):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr
arr = [64, 34, 25, 12, 22, 11, 90]
sorted_arr = bubble_sort(arr)
print("排序后的数组：", sorted_arr)
================================
but using 'copy' or 'insert in editor', the code will be:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(0, n - i - 1):
            if arr[j] & gt; arr[j+1]:        <-------- 
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr
arr = [64, 34, 25, 12, 22, 11, 90]
sorted_arr = bubble_sort(arr)
print( & quot;     
排序后的数组： & quot;, sorted_arr)   <--------

**Comment by Chenjiangwen** [comment]
example:
the code generated by chatGPT:
`def bubble_sort(arr):
n = len(arr)
for i in range(n-1):
for j in range(0, n-i-1):
if arr[j] > arr[j+1]:
arr[j], arr[j+1] = arr[j+1], arr[j]
return arr
arr = [64, 34, 25, 12, 22, 11, 90]
sorted_arr = bubble_sort(arr)
print("排序后的数组：", sorted_arr)`

but using 'copy' or 'insert in editor', the code will be:
`def bubble_sort(arr):
n = len(arr)
for i in range(n - 1):
for j in range(0, n - i - 1):
if arr[j] & gt; arr[j+1]: <--------
arr[j], arr[j + 1] = arr[j + 1], arr[j]
return arr
arr = [64, 34, 25, 12, 22, 11, 90]
sorted_arr = bubble_sort(arr)
print( & quot;
排序后的数组： & quot;, sorted_arr) <--------`

**Comment by obiscr** [comment]
Thanks, In my tests, copying does not work, but Insert to Editor is fine. It will be fixed in a later version.

**Comment by obiscr** [comment]
This issue has been fixed in version 3.1.2. please update to latest version.
