### ISSUE TITLE
无法通过快捷键操作

### ISSUE THREAD

**Issue by geekerzhou** [obiscr/ChatGPT#271]
chatgpt 官方网页，一打开，焦点默认就在输入框了，直接打字就行。这个插件打开 tool window 之后，必须用鼠标点击输入框才能打字，每次新打开都需要这么操作。不能键盘操作，很麻烦。希望能给输入框加个快捷键，可以快速定位到输入框

**Comment by obiscr** [comment]
感谢，这是个好建议。

**Comment by obiscr** [comment]
它将会在下个版本中得到修复。

**Comment by obiscr** [comment]
This issue has been fixed in version [3.1.2](https://chatgpt.gold/release/3.1.2/). please update to latest version.
