### ISSUE TITLE
Can't enable inline auto complete. There is no settings for it

### ISSUE THREAD

**Issue by lao2r** [obiscr/ChatGPT#272]
There is no settings for enable Inline auto completion. 
Version - 3.1.1-223
![image](https://github.com/obiscr/ChatGPT/assets/83645806/23a5a232-e6d6-4e2b-8161-ac8f31237165)

Has this feature been disabled?

**Comment by obiscr** [comment]
Sorry I didn't make it clear in the documentation before, because of SDK compatibility, Inline Complete only supports 2023.1 and later versions.
