### ISSUE TITLE
[Feature Request] Comment code

### ISSUE THREAD

**Issue by angeousta** [obiscr/ChatGPT#274]
1. You select a portion of code (or a file)
2. Right click on the selected code (or file)
3. Menu => Ask ChatGpt => Comment

And the code gets commented

**Comment by obiscr** [comment]
I'm sorry, I didn't quite understand. Could you be more specific?

**Comment by obiscr** [comment]
This is a good idea. We currently have an ask codebase function to process the entire file: https://chatgpt.gold/blog/posts/2023/Ask-codebase-is-now-supported/

So there is no feature to provide ask gpt for individual files, currently only selected text is supported though. We will consider whether adding this feature at a later.
