### ISSUE TITLE
The newest plugin will set my editor font size to 14.0.

### ISSUE THREAD

**Issue by Amoseriy** [obiscr/ChatGPT#278]
Today I update the plugin and I found that the plugin will set my editor font size to 14.0 when I open Pycharm. Just like the font size of the plugin.
![image](https://github.com/obiscr/ChatGPT/assets/35002587/6402df23-5c61-4d8e-ac41-9aa0b9886cc0)
![image](https://github.com/obiscr/ChatGPT/assets/35002587/711dac83-cdc9-4f3b-b08e-384d0a3a6e5c)

And when I disable the plugin, this problem will be solved.

My Pycharm version is 2023.2.

**Comment by obiscr** [comment]
Thank you, It will be fixed in next release.

**Comment by obiscr** [comment]
It has been fixed in version [3.1.3](https://chatgpt.gold/release/3.1.3/)

**Comment by Amoseriy** [comment]
OK, nice job :)
