### ISSUE TITLE
ChatGPT: 请求服务器错误

### ISSUE THREAD

**Issue by k99k5** [obiscr/ChatGPT#28]
Http 响应码: 403, 响应信息: Forbidden.
网页是正常访问的，插件时最新的

**Comment by yuanhao1998** [comment]
我也有同样的问题，是自己配置的官方源，网页使用正常

**Comment by obiscr** [comment]
Open AI服务器更新了，导致大面积的无法访问。目前请求国内源返回500，请求官方源返回403。
API访问都被屏蔽了。浏览器可以访问。
目前临时折中的办法是在IDE里面内嵌了浏览器。最新的1.0.7的版本正在审核。审核通过后就现在查件使用浏览器来访问。
