### ISSUE TITLE
Cannot re-map ShiftTabAction

### ISSUE THREAD

**Issue by sergiotula** [obiscr/ChatGPT#281]
PhpStorm version: #PS-232.8660.205
Plugin version : 3.1.3-231.232

The ShiftTabAction cannot be re-mapped to any other key shortcut. It cannot even be removed. It will always use the "Shift-Tab" combination no matter what.

**Comment by obiscr** [comment]
Hi @sergiotula, currently there is a real problem with the buttons on this feature, we will fix it as soon as possible!

**Comment by obiscr** [comment]
It has been fixed at v3.1.5, please upgrade to version 3.1.5.
