### ISSUE TITLE
在2023.2.1下暗黑主题显示配色难以查看

### ISSUE THREAD

**Issue by shiqi-lu** [obiscr/ChatGPT#282]
在2023.2.1下暗黑主题显示的字体颜色较难辨认，如图所示，可否调整配色，如底色是黑色，文字是白色
<img width="428" alt="image" src="https://github.com/obiscr/ChatGPT/assets/8554684/9dbef4f6-3da9-4317-a107-a054c1c77999">

**Comment by obiscr** [comment]
这种情况应该是跟使用的主题有关系，能否尝试重启IDE，或者切换到其他主题看是否正常 ？

**Comment by shiqi-lu** [comment]
Light主题是没问题的，就是Dark、Darcula、High contrast主题显示会的配色会难以辨别，这个可否后续适配下呢

**Comment by obiscr** [comment]
这个确实如此，因为切换主题并不是一个高频操作。因此只需要重启下就可以。关于后续是否适配，暂时不确定。

**Comment by obiscr** [comment]
暂时没有计划，这个issue先关闭了，后期有需要会再次打开。
