### ISSUE TITLE
pycharm中设置代理无效

### ISSUE THREAD

**Issue by lxt20180608** [obiscr/ChatGPT#284]
网络环境：Clash for Windows
OpenAI：使用经过cf-openai-azure-proxy转换的Azure OpenAI代理，已测试在其他浏览器插件中自定义api地址和密钥有效，且clash中看到了pycharm中自定义的api地址走代理的记录
设置如下：
https://z1.ax1x.com/2023/09/15/pPWtvy8.png
发送消息返回的错误如下：
Response failure, please try again. Error message: 404 Not Found

请问是哪里没有配置对呢？

**Comment by obiscr** [comment]
您的代理看起来似乎是正确的，能否看下自定义server的配置？
可以先不要使用自定义的server，先使用默认的server。来检查代理是否生效。

**Comment by obiscr** [comment]
![image](https://github.com/obiscr/ChatGPT/assets/28687074/5ff18f5d-e28c-40ba-ac8b-1c0c0984956d)
我明白了，请问在您的设置中，这里配置的是私有的Azure 地址吗？

**Comment by lxt20180608** [comment]
是的，没错

**Comment by obiscr** [comment]
目前可能不能兼容azure的 endpoint，之前有过一个类似的 #183 ：但是还没有来得及完成。

**Comment by lxt20180608** [comment]
好的，感谢回复

**Comment by obiscr** [comment]
没关系，后续关于azure的进可以关注 #183，感谢！
