### ISSUE TITLE
Codebase index failed on WebStorm 2023.2.2

### ISSUE THREAD

**Issue by stoyan-kalinov** [obiscr/ChatGPT#286]
Problem:
Whenever I try to index the codebase it fails. Doesnt matter how many file I choose to be indexed...

![image](https://github.com/obiscr/ChatGPT/assets/132346411/874c4f08-5ee7-4470-af0e-c466a9ccf14e)

![image](https://github.com/obiscr/ChatGPT/assets/132346411/26a35294-2055-4132-a395-b799cd07704f)

![image](https://github.com/obiscr/ChatGPT/assets/132346411/584cef69-2455-4994-9f2c-fe5e2db53c55)
 
The other problem for which I have asked the support is that I firstly subscribed for the biggest plan -> I was charged -> then I tried the codebase indexing and it was failing -> Then maybe because of my mistake I didnt red correctly I downgraded to the GPT 3.5 Pro plan -> I was charged again for $7 -> Then after that I couldnt get back to the biggest plan which I was already charged ->
I then subscibed again to the biggest plan -> I am charged again

I was using revolut card if that matters but the things is that I am now charged 3xTimes. So I will wait for response and also money back for 2 of the charges -> 1xBiggest plan and 1x3.5 Pro Plan

**Comment by obiscr** [comment]
Hello @stoyan-kalinov 

Please send your `idea.log` and `easycode account` to my [email](wuzi@obiscr.com)
And regarding being charged repeatedly, we will verify it and keep you posted via email.

Thank you!
