### ISSUE TITLE
Client challenge required

### ISSUE THREAD

**Issue by Miofly** [obiscr/ChatGPT#287]
Response failure, please try again. Error message: {"detail":{"message":"Client challenge required","code":"challenge_required"}}

**Comment by obiscr** [comment]
Currently encountering an openai issue, that may not work for some users

![image](https://github.com/obiscr/ChatGPT/assets/28687074/eb158d0e-eab5-4eb2-ba46-11cce76b6028)

**Comment by obiscr** [comment]
It has been fixed. Thanks!
