### ISSUE TITLE
Response failure, please try again.

### ISSUE THREAD

**Issue by yahao-li** [obiscr/ChatGPT#288]
Response failure, please try again. Error message: {"cf_details":"Something went wrong. Please contact Support.", "type":"dc"}

**Comment by Miofly** [comment]
same error

**Comment by obiscr** [comment]
Hi, this issue was a duplicate of #287  and now looks to be fixed. Could you try it again?

**Comment by dalaverd** [comment]
I still have this issue since yesterday

**Comment by obiscr** [comment]
This issue has been fixed, thanks.

**Comment by dalaverd** [comment]
![image](https://github.com/obiscr/ChatGPT/assets/4228254/57eff052-6d7c-404b-9cca-d9428b1c6279)
