### ISSUE TITLE
Response failure, request is not allowed

### ISSUE THREAD

**Issue by dalaverd** [obiscr/ChatGPT#289]
Using ChatGPT on model GPT4 since last week I am getting this error :

![image](https://github.com/obiscr/ChatGPT/assets/4228254/87a25484-033e-4db9-abfc-946cb1f5d717)

**Comment by obiscr** [comment]
Hi, may I ask which tab has this issue.

**Comment by dalaverd** [comment]
ChatGPT

**Comment by obiscr** [comment]
Okay, I'm testing fine now, can you test if it's working now, if not, please let me know your plugin version, ide version. 

![image](https://github.com/obiscr/ChatGPT/assets/28687074/5c8c29ce-4511-4f93-a059-0d2b70e5e119)

**Comment by dalaverd** [comment]
I am still getting the same error. Are you sure you are using model gpt4? I am only getting this issue with that model.

Plugin ver: 3.1.5-231.232
Ide (webstorm) ver:  2023.2.3

**Comment by obiscr** [comment]
Sorry, I don't have a gpt-4 account on my side at the moment. I'm not sure if this was caused by the same reason (OpenAI) as #292 , and #292 is fine now.

**Comment by dalaverd-canac** [comment]
I'm still encountering this issue as of 2023-11-01. Has there been any progress or updates on a potential fix? Thanks for any insights.

**Comment by dalaverd** [comment]
I'm still encountering this issue as of 2023-11-01. Has there been any progress or updates on a potential fix? Thanks for any insights.

**Comment by obiscr** [comment]
@dalaverd 

At the beginning of this problem with OpenAI, many people had this problem. After a few hours, OpenAI's service was restored and the issue was fixed automatically. Strictly speaking, it doesn't look like an issue with the extension itself. The extension didn't make any changes or fixes in this regard either. 

Because of that, I'm guessing that you may have some other issue causing this.

Could you send your idea.log to wuzi@obiscr.com? I will be happy to fix this issue.

**Comment by dalaverd** [comment]
I encountered this error (found in idea.log) while trying to initiate a conversation with ChatGPT. Here's the stack trace:

```
2023-11-01 09:44:04,655 [ 278182]   INFO - a.a.a.C - ChatGPT: conversation failure. Url=https://ai.fakeopen.com/api/conversation, response=Response{protocol=h2, code=403, message=, url=https://ai.fakeopen.com/api/conversation}
```

Any assistance in resolving this would be appreciated.

**Comment by obiscr** [comment]
I was able to access it with the same URL and AI answered normally. It looks like it's still a network issue, can you switch networks (to a different IP, you can use the proxy tool) to see if you can access it properly.

**Comment by dalaverd** [comment]
Are you sure you were using this model?
![image](https://github.com/obiscr/ChatGPT/assets/4228254/1d522206-a799-4f7a-8364-e6c0baab4494)
Even by switching network, I still get the same error. Also, it was working before.

**Comment by obiscr** [comment]
You are right, when I use the gpt-4 model I get the same error. 
Sorry, this cannot be fixed for now. To use GPT-4, a temporary solution is to consider using EasyCode Tab, which also provides GPT-4 support.

**Comment by obiscr** [comment]
I understand what you are saying. And sorry for the trouble caused by this issue, I will let you know once this issue is fixed.

**Comment by joseffb-mla** [comment]
Same issue. I also have a gpt4 sub and aren't a fan of duplicitous subscriptions. Good plugin so far though so thank you for your hard work Wuzi!

**Comment by obiscr** [comment]
Sorry, after my tests in the last few days, now ChatGPT Tab can't do this, it should be limited by the server Proxy.

There are two options to try:
1. Using GPT-3.5-Turbo Tab, change the model to `gpt-4-xxx` in the [gpt-3.5-turbo settings](https://chatgpt.gold/settings/gpt-3.5-turbo-settings/), this should be available.
  > No need to pay again, use your original openai account, provided it has been upgraded to Plus
2. Use EasyCode Tab
  > you need to sign up for an EasyCode account and buy GPT-4 Credits

**Comment by obiscr** [comment]
This issue is out of date and it will be closed. Also, please update to latest version 3.3.1.
