### ISSUE TITLE
Not a JSON Object: null

### ISSUE THREAD

**Issue by Miofly** [obiscr/ChatGPT#290]
A new error has occurred Not a JSON Object: null

**Comment by obiscr** [comment]
Hi could you describe which tab caused this problem?

**Comment by Miofly** [comment]
> Hi could you describe which tab caused this problem?

chatgpt
<img width="595" alt="image" src="https://github.com/obiscr/ChatGPT/assets/42859910/8e50e461-a358-49ec-9e89-f01253e99067">

**Comment by obiscr** [comment]
Okay, I'm testing fine now, can you test if it's working now, if not, please let me know your plugin version, ide version.

![](https://user-images.githubusercontent.com/28687074/277675948-5c8c29ce-4511-4f93-a059-0d2b70e5e119.png)

**Comment by Miofly** [comment]
<img width="478" alt="image" src="https://github.com/obiscr/ChatGPT/assets/42859910/891533a2-f3a7-4b47-84a5-a150b40c5e18">
<img width="512" alt="image" src="https://github.com/obiscr/ChatGPT/assets/42859910/18027a6f-734b-490c-a41b-9cecd27b440b">

**Comment by haldon98** [comment]
I have the same problem. The rider 's version is 2022.2.3, plugin version is 3.1.5-203.222.4

**Comment by haldon98** [comment]
> Okay, I'm testing fine now, can you test if it's working now, if not, please let me know your plugin version, ide version.
> 
> ![](https://user-images.githubusercontent.com/28687074/277675948-5c8c29ce-4511-4f93-a059-0d2b70e5e119.png)

我用的rider2022.2.3，插件是3.1.5-203.222.4。我发现偶尔第一次打开IDE，第一条是会回复的，然后就都是Not a JSON Object: null。我升级了rider到2023.2.2，插件升级到了3.1.5-231.232都不行，麻烦您帮忙看看是什么问题，谢谢啦

**Comment by Miofly** [comment]
now is normal
