### ISSUE TITLE
Not a JSON Object: 

### ISSUE THREAD

**Issue by qizhuocai** [obiscr/ChatGPT#292]
去网站可以对话，在插件里面对话不会返回，但是网站的对话正常显示。昨天开始不行的
![image](https://github.com/obiscr/ChatGPT/assets/20677983/f0d278bf-117a-472a-bc6c-76246b52b4c1)
![image](https://github.com/obiscr/ChatGPT/assets/20677983/dc920f02-8e84-407f-a09d-d333d23c71fe)

![image](https://github.com/obiscr/ChatGPT/assets/20677983/0ea6846b-97b8-49b8-9d1d-4a05a0ae823b)

**Comment by haldon98** [comment]
今天好像突然又好了

**Comment by obiscr** [comment]
好的，这应该是OpenAI那边的故障。感谢！
