### ISSUE TITLE
插件在IDE登录的时候提示 error code

### ISSUE THREAD

**Issue by obiscr** [obiscr/ChatGPT#293]
插件在IDE登录的时候提示 error code

_Originally posted by @Malkweiyuan in https://github.com/obiscr/ChatGPT/issues/183#issuecomment-1788655567_

**Comment by obiscr** [comment]
@Malkweiyuan 能否提供更多的详细信息，例如 IDE版本，插件版本。以及一些截图，或者错误日志等信息？

**Comment by Malkweiyuan** [comment]
对应截图和版本


weiyuan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obiscr/ChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obiscr/ChatGPT] 插件在IDE登录的时候提示 error code (Issue #293)





 
@Malkweiyuan 能否提供更多的详细信息，例如 IDE版本，插件版本。以及一些截图，或者错误日志等信息？

**Comment by Malkweiyuan** [comment]
没有注册的原因导致的




weiyuan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obiscr/ChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obiscr/ChatGPT] 插件在IDE登录的时候提示 error code (Issue #293)





 
@Malkweiyuan 能否提供更多的详细信息，例如 IDE版本，插件版本。以及一些截图，或者错误日志等信息？

**Comment by obiscr** [comment]
Okay, 那请问现在正常了吧？

**Comment by Malkweiyuan** [comment]
正常了，可以设置为自动提示吗？或者有没有对应的参考文档


 
Okay, 那请问现在正常了吧？

**Comment by obiscr** [comment]
后面会改进这一点，谢谢
