### ISSUE TITLE
Custom OpenAI API model name

### ISSUE THREAD

**Issue by paullallier** [obiscr/ChatGPT#294]
I don't think this is a duplicate of #190 - sorry if it is.

Would it be possible to have an option to manually enter a model name rather than just selecting from a pre-set list, please?  Obviously, I'm most interested in gpt-4-1106-preview at the moment, which will probably evolve to gpt-4-turbo in a few weeks, but if they are going to start hosting custom models, a free-text model name field would be useful.

Assuming, of course, that the syntax on the API for calling the different models isn't completely different - I've not looked.

**Comment by obiscr** [comment]
There is no problem with adding custom models. Regarding the API, it should be the same.

**Comment by dmitrii-maksimov** [comment]
@obiscr please explain how to add?

**Comment by obiscr** [comment]
The new version 3.1.7 is under review, and once it's approved, the model can be customised!

**Comment by obiscr** [comment]
Hi, please update to latest version [3.1.7](https://chatgpt.gold/release/3.1.7/#custom-openai-api-model), this issue is fixed
