### ISSUE TITLE
Response failure, please try again. Error message: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}

### ISSUE THREAD

**Issue by GuitarChen** [obiscr/ChatGPT#297]
![1700545187023](https://github.com/obiscr/ChatGPT/assets/18723138/657050f5-e4a4-439a-abee-7b6f478ee0e8)

**Comment by obiscr** [comment]
ChatGPT Tab is currently unavailable because of the server.

**Comment by obiscr** [comment]
We recommend using the EasyCode Tab, or the GPT-3.5-Turbo tab first! They both support GPT-4.

**Comment by inetkachev** [comment]
> We recommend using the EasyCode Tab, or the GPT-3.5-Turbo tab first! They both support GPT-4.

Have same issue with api keys. 
About your "workaround". For EasyCode tab permanent "Login failed" (double checked credentials).

**Comment by GuitarChen** [comment]
ok thanks

**Comment by ShantanuRauthan** [comment]
i am still getting this issue, im on gpt free version

**Comment by obiscr** [comment]
Yep, it is still recommend using the EasyCode Tab, or the GPT-3.5-Turbo tab.

**Comment by HaldonFu** [comment]
@obiscr 作者大大，请问有没有加入可让用户自己部署pandora-next，用access_token使用gpt的计划？像chatgpt tab那样

**Comment by obiscr** [comment]
@HaldonFu 您好，暂时没有这个计划。

**Comment by obiscr** [comment]
Hello guys, we decided to remove ChatGPT Tab in 3.2.0 or later version. Please use the EasyCode Tab or OpenAI API Tab instead.
