### ISSUE TITLE
Waiting for response...

### ISSUE THREAD

**Issue by 6ddds1** [obiscr/ChatGPT#298]
GPT 3.5 Turbo Request failure, cause: Failed to connect to api.openai.com/104.244.46.85:443

**Comment by obiscr** [comment]
It looks like your network is unable to connect to OpenAI's servers.
This depends on the network environment/region/country you are in. You may need to configure the Proxy for proper access.
You can configure the proxy at [Proxy Settings](https://chatgpt.gold/settings/openai-settings/#proxy-settings).
