### ISSUE TITLE
插件市场搜不到

### ISSUE THREAD

**Issue by ybwhat** [obiscr/ChatGPT#3]
插件市场搜不到啊
![image](https://user-images.githubusercontent.com/50785063/206663725-6861ba25-5eb7-4957-9b36-9eaf9fc3e7f1.png)

**Comment by obiscr** [comment]
您好，目前插件还在审核，可以先在此处下载。
https://plugins.jetbrains.com/files/20603/263839/ChatGPT-1.0.1.zip

另外，可以下载的时候我会在微信群第一时间通知。感兴趣可以加下。
加群链接：https://www.obiscr.com/article/Wechat-group-is-now-open

**Comment by ybwhat** [comment]
好的谢谢

**Comment by obiscr** [comment]
@ybwhat 下载地址我修改了一下，用最新的：https://plugins.jetbrains.com/files/20603/263857/ChatGPT-1.0.1.zip

**Comment by obiscr** [comment]
插件现在已经开放下载了：https://plugins.jetbrains.com/plugin/20603-chatgpt
