### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by davemaxg** [obiscr/ChatGPT#30]
I was able to set the token but after that, I can't figure out how to open the window that I see on the screenshots so I can access ChatGPT from within the IDE. Nor do I see how it's integrated with the IDE.  I was thinking that perhaps I could have the AI write code that is inserted as well as be able to explain existing code snippets...

I am using PHPStorm.

Please help.

**Comment by obiscr** [comment]
It's in the tool window on the right side of the IDE. Please watch [this video](https://www.bilibili.com/video/BV1qV4y1P7Qh/), although it is in Chinese. But I believe there should be no problem.

In addition, it is very unfortunate that Cloudflare protection has been added to OpenAI's server recently, which makes it unable to be used normally. When you send an Http request, it will respond with 403. I'm currently looking for other alternatives.

**Comment by davemaxg** [comment]
Thank you so much for responding and for making the plug in. I am unable to follow the video and it sounds like the plug in doesn't work at the moment anyway?  Watching... :)

**Comment by obiscr** [comment]
Yes, because of the OpenAI official server, the API is temporarily unavailable. But the embedded browser can be used.
