### ISSUE TITLE
我怎么使用API去回答Custom Prompt？

### ISSUE THREAD

**Issue by NOforgetQY** [obiscr/ChatGPT#303]
我记得之前没有EasyCode时，使用Custom Prompt是会采用ChatGPT API 回复的，但是现在好像只能使用EasyCode，如果EasyCode账户里没有额度了，那是不是就用不了Custom Prompt了，我能不能选择在使用Custom Prompt时是调用EasyCode或者ChatGPT API呢？

**Comment by obiscr** [comment]
您好，这取决于当前正在使用的Tab。切换到哪个Tab，就会在哪个Tab中回答。

**Comment by NOforgetQY** [comment]
好吧，确实是这样，会有这个问题是因为我之前没有登录，所以即使切换带API的Tab，它也依旧会调用EasyCode然后报错，现在我登陆后就没有问题了，在哪个Tab就会是哪个Tab回答，非常感谢！
