### ISSUE TITLE
IDEA 2023.3 无法使用 Inline autocomplete ，Shitf-Tab 无反应

### ISSUE THREAD

**Issue by kongxubihai** [obiscr/ChatGPT#310]
1、IEDA 2023.3 无法使用 Inline autocomplete ，Shift-Tab 无反应
2、 Inline autocomplete 也无法自定义快捷键
![image](https://github.com/obiscr/ChatGPT/assets/29792005/a87764a3-f84c-4bf5-a535-ef84d407a995)

**Comment by obiscr** [comment]
您好，这个feature我们计划会在未来移除，非常抱歉给您带来不便。

**Comment by obiscr** [comment]
This issue has expired and will be closed.
