### ISSUE TITLE
OpenAI API doesn't work

### ISSUE THREAD

**Issue by NovaGTX** [obiscr/ChatGPT#311]
I've configured the API Key. I've tried every model, even custom labeling based on what Open AI says is available. Every time it fails and give an error "The model `gpt-4` does not exist or you do not have access to it."  I have GPT+ so I know it's not a permission issue.

**Comment by obiscr** [comment]
Hi, Would you mind sharing your api configuration please?
**Please be careful not to expose your api key (sensitive information)**

This is my current configuration and it works fine.
![image](https://github.com/obiscr/ChatGPT/assets/28687074/6171e4e9-6a83-4470-afaa-7a8422637015)

**Comment by NovaGTX** [comment]
Thanks for the quick reply, I was out of credits 🤣

**Comment by NovaGTX** [comment]
close.
