### ISSUE TITLE
新版自动完全是不是没了

### ISSUE THREAD

**Issue by vvv1235135** [obiscr/ChatGPT#312]
SHIFT+TAB没反应，看快捷键里面也没有这个组合键

**Comment by obiscr** [comment]
是的，我们会在以后的版本移除这个功能。

**Comment by vvv1235135** [comment]
这个自动完成是需要我按快捷键来触发的么

**Comment by vvv1235135** [comment]
那好吧，我本想学习一下需要提供什么样的上下文给api进行代码补全的，我目前提供的上下文就单纯的光标处到代码第一行的内容，但是有tokens限制，导致我必须换个思路

**Comment by obiscr** [comment]
是的，抱歉。您可以关注下我们的下个版本。
