### ISSUE TITLE
online chatgpt tabs

### ISSUE THREAD

**Issue by shine-ztf** [obiscr/ChatGPT#313]
在online chatgpt打开的web页面，输入框无法使用enter键发送

**Comment by shine-ztf** [comment]
On the web page of online chatgpt, the input box cannot send messages using the enter key. hope this issue can be resolved

**Comment by obiscr** [comment]
你好，在 [3.3.1](https://chatgpt.gold/release/3.3.1/#online-chatgpt-support-customize-url-optimize-ux) 版本中，对Online ChatGPT Tab做了新的改进，这个问题已修复。另外，Online ChatGPT Tab已过时，会在未来的版本中移除。见 [issue#317](https://github.com/obiscr/ChatGPT/issues/317)
