### ISSUE TITLE
shift+tab不能自动补全代码

### ISSUE THREAD

**Issue by paysion** [obiscr/ChatGPT#315]
我的idea版本是2021，安装了chatgpt-easycode插件，侧边的聊天栏是没问题的，但是使用shift+tab补全代码时，idea会卡住。我怀疑是快捷键冲突的问题，检查idea确实存在shif+tab快捷键。可是，我并不是修改idea的快捷键，因为我不确定是不是快捷键的问题。

所以，我有两个问题：
- 插件本身能不能修改自动生成代码的快捷键呢？
- 怎么解决我的代码自动补全问题？

**Comment by obiscr** [comment]
您好，目前的版本自动补全暂时无法使用，预计会在下个版本或者下下个版本可用。
