### ISSUE TITLE
what？

### ISSUE THREAD

**Issue by 18801151992** [obiscr/ChatGPT#319]
Response failure, please try again. Error message: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"

**Comment by 18801151992** [comment]
<img width="515" alt="image" src="https://github.com/obiscr/ChatGPT/assets/25807952/6b0c7fff-873b-4ebd-93f2-82a10ba0f91e">

**Comment by obiscr** [comment]
Hi, this plugin is deprecated, please use the **ChatGPT - EasyCode** plugin instead.
