### ISSUE TITLE
在PyCharm中安装该插件时，显示一片空白

### ISSUE THREAD

**Issue by zhaijinhua** [obiscr/ChatGPT#34]
您好，我尝试了很久始终无法在PyCharm中使用该插件，请帮忙看看问题：
版本信息：PyCharm 2021.1.3, python 3.10
问题描述：不论是使用入门文档中的“一键安装”还是“使用内置插件系统”安装，在使用的时候并没有演示视频上有“使用说明”之类的描述，并在后续使用“发送”按钮时无任何提示也没有结果，本人以配置了官方的API KEY，并且使用在线ChatGPT是没问题的
![image](https://user-images.githubusercontent.com/62973325/210695566-af6c3b17-b277-41d1-a64d-c4b897c16c0f.png)
![image](https://user-images.githubusercontent.com/62973325/210695853-6c2927f1-ce0e-43aa-bfa6-af58973037b3.png)
![image](https://user-images.githubusercontent.com/62973325/210696116-7226cd17-878c-4469-90f7-4703d13bc62a.png)

**Comment by obiscr** [comment]
很抱歉，回复迟了。能否重新安装一下插件，等安装完成以后，在ide打开一下插件，并且提供一下ide的日志（Help -> Show log in explorer, 复制 idea.log），麻烦发到我的邮箱 wuzi@obiscr.com 。

或者您是不是安装了其他类似的ChatGPT的插件，可以检查一下。

**Comment by obiscr** [comment]
This issus is temporarily closed. I'll open it later if needed.
