### ISSUE TITLE
我的IDE是Intellij IDEA

### ISSUE THREAD

**Issue by Skyline875** [obiscr/ChatGPT#35]
我的IDE下完chatGPT之后右侧的栏目里并没有chatGPT,重试了好几遍也都没有，跟你所说的不符合情况，希望能帮我解决一下，谢谢

**Comment by obiscr** [comment]
感谢反馈！
请问是不是之前还安装了其他的插件，或者请提供一下 idea.log ，IDE 版本，插件版本等信息。

**Comment by obiscr** [comment]
This issus is temporarily closed. I'll open it later if needed.
