### ISSUE TITLE
官方源报错400/Official source error 400

### ISSUE THREAD

**Issue by 56dot1** [obiscr/ChatGPT#39]
你好，我的pycharm版本为2020.3.2，将api-key复制粘贴进去后无法正常使用:-(，使用右键中的解释代码或找出问题就会出现报400的错，我该把clash调整成全局模式？或者做些其他的事来解决该问题？

Hello, my PyCharm version is 2020.3.2, after copying and pasting the api-key, it can't be used normally, when using the right-click to explain the code or find the problem, it will report error 400, should I adjust clash to global mode? or do something else to solve the problem?

**Comment by obiscr** [comment]
请问如果用英文是否可以正常使用？您还可以尝试设置一下编码，编码的设置请参考这里：https://docs.obiscr.com/article/GPT-QA
