### ISSUE TITLE
插件请求400

### ISSUE THREAD

**Issue by changzhongxinxin** [obiscr/ChatGPT#43]
报400错误
![snipaste_20230131_113302](https://user-images.githubusercontent.com/68383493/215656585-cc7a4b1d-e1d5-48e2-920d-3ba9736d6f82.png)

**Comment by obiscr** [comment]
应该是编码问题，请先参考：https://docs.obiscr.com/article/GPT-QA 尝试解决。

**Comment by changzhongxinxin** [comment]
可以了了，只改了第一个文件就ok了
