### ISSUE TITLE
打开session网站  没有数据

### ISSUE THREAD

**Issue by 75ACOL** [obiscr/ChatGPT#44]

**Comment by 75ACOL** [comment]
还能用么 这个工具 我看你还在更新

**Comment by obiscr** [comment]
还在更新，关于您说的问题，请提供一下截图

**Comment by 75ACOL** [comment]
刚刚有数据了，很奇怪。感谢。我想问问你能不能做成聊天的形式，就是会记录你的上下文，相等于openAI的网站那样

**Comment by 75ACOL** [comment]
https://api.openai.com/v1/completions 这个api各个参数我不是很理解 你有中文文档么

**Comment by obiscr** [comment]
> https://api.openai.com/v1/completions 这个api各个参数我不是很理解 你有中文文档么

这个是OpenAI返回的，我的文档在这里：https://docs.obiscr.com/article/GPT

**Comment by 75ACOL** [comment]
感谢你的回答，但是你的网址打不开

**Comment by obiscr** [comment]
> 刚刚有数据了，很奇怪。感谢。我想问问你能不能做成聊天的形式，就是会记录你的上下文，相等于openAI的网站那样

目前2.0.0版本支持聊天的那种形式展示。
