### ISSUE TITLE
中文回答显示乱码

### ISSUE THREAD

**Issue by lldhliu** [obiscr/ChatGPT#46]
pycharm  chatgpt的中文回答显示乱码

**Comment by obiscr** [comment]
感谢反馈，会尽快处理，临时的解决方案如下：

点击 Help -> Edit Custom VM Options...

添加 -Dfile.encoding=UTF-8 到 vmoptions 文件

![image](https://user-images.githubusercontent.com/28687074/217456359-44d5272c-d530-48b8-8f7f-79d1c7d50935.png)

重新启动IDE即可解决。
