### ISSUE TITLE
Old answers shouldn't get cleared when you ask a new question

### ISSUE THREAD

**Issue by bitspittle** [obiscr/ChatGPT#5]
You can have conversations with ChatGPT, for example, asking it to refind a previous answer.

I belive it would be useful, therefore, to keep old answers around.

**Comment by obiscr** [comment]
Yes, it's a great idea, it's just getting off the ground, there's a lot that could be improved, and I'll put this in the future feature list. Thank you for your suggestion.

**Comment by bitspittle** [comment]
Good on you for moving so fast :) Good luck with the project!

**Comment by shlomich** [comment]
I just wanted to find a place to say thank you for this plugin! Great suggestion btw.

**Comment by richardkkk** [comment]
Additionly, please add the function of **editing questions** as same as the official website.

**Comment by obiscr** [comment]
> Additionly, please add the function of **editing questions** as same as the official website.

Yes, this is very useful!
