### ISSUE TITLE
Google 帐号无法登录

### ISSUE THREAD

**Issue by fondantcn** [obiscr/ChatGPT#52]
此浏览器或应用可能不安全。
请尝试使用其他浏览器。如果您使用的是受支持的浏览器，可以重新尝试登录。

**Comment by fondantcn** [comment]
在线ChatGPT中无法使用Google 帐号登录

**Comment by obiscr** [comment]
我不得不说我对这个问题感到抱歉。 这个问题似乎是谷歌的问题。 插件本身对谷歌登录没有限制。 你可以看这里：https://github.com/m1guelpf/chatgpt-telegram/issues/4
