### ISSUE TITLE
用中文提问，gpt返回显示乱码

### ISSUE THREAD

**Issue by longxiaohai** [obiscr/ChatGPT#53]
如题，输入如何学习C++
ChatGPT返回乱码。
是否有相关编码配置？
![image](https://user-images.githubusercontent.com/28552380/218078953-46bceaee-8ba1-4586-8418-2efb1a4bc748.png)

**Comment by obiscr** [comment]
最新的版本已经更新了。如果您更新到2.0.2的版本，那就应该不会有这个问题了

**Comment by longxiaohai** [comment]
感谢！2.0.2中文乱码已解决。
