### ISSUE TITLE
english please

### ISSUE THREAD

**Issue by landsman** [obiscr/ChatGPT#54]
Whole plugin probably speaking chinese to me?
Can you please add english i18n? https://www.deepl.com could help.

**Comment by obiscr** [comment]
Thank you for your feedback. I will support you as soon as possible.

**Comment by obiscr** [comment]
@landsman Please update to the latest version 2.0.3, this issue will be fixed.

**Comment by landsman** [comment]
Hi, is it possible to use [GitHub Releases](https://github.com/obiscr/ChatGPT/releases)?
I use to check it to see what's changed in which version etc. 
From my POV it's the best way to keep changelog for everyone.

**Comment by obiscr** [comment]
@landsman Thanks for the feedback, I'll be using GitHub Releases in the near future. I've been busy recently. So I didn't have time to organize the Release.
