### ISSUE TITLE
Couldn't sign you in... Google Login

### ISSUE THREAD

**Issue by cybersholt** [obiscr/ChatGPT#57]
Tried to login with Google and got the following error message 

```
Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
```

It would be great if it opened the default browser vs how it's implemented now. 

Editor: PhpStorm 2022.3.2 
Host: Windows 10 
Chat GPT Plugin Version: 2.0.2-222.223

![Warning](https://i.imgur.com/wRUDtTl.png)

**Comment by obiscr** [comment]
I have to say I'm sorry about this problem. This problem seems to be Google's problem. The plugin itself has no restrictions on Google login. You can look here：https://github.com/m1guelpf/chatgpt-telegram/issues/4
