### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by gmanc2** [obiscr/ChatGPT#59]
Whenever I try to submit my code I get 
![image](https://user-images.githubusercontent.com/4944080/218374422-1da2c52c-b970-4f5c-ac1d-4ebe40ad1f0d.png)
Is my code too long? When I type hello or any other text it works fine but when I try to submit my code it doesn't work.

**Comment by obiscr** [comment]
This is the message returned by OpenAI's official server. Probably because their servers are overloaded.
