### ISSUE TITLE
自定义模式——对话 我 显示null

### ISSUE THREAD

**Issue by anple** [obiscr/ChatGPT#65]
![E0B148E3-A4BC-4ffb-852C-C16D23DB1812](https://user-images.githubusercontent.com/13133125/219279360-27f31fc7-5835-4a39-8dbc-97952ffbc0e5.png)
![DEEAA3BC-EA98-4cbd-917B-BD5BBF16692C](https://user-images.githubusercontent.com/13133125/219279692-8a663044-6cad-42c1-909b-78571408d0ba.png)

**Comment by anple** [comment]
看了源代码应该是少调用了buildQuestion

**Comment by obiscr** [comment]
感谢反馈，后期会修复

**Comment by obiscr** [comment]
请更新到最新版，这个问题已经被修复了。
