### ISSUE TITLE
为什么参考插件源码调用返回403？

### ISSUE THREAD

**Issue by 77981836** [obiscr/ChatGPT#67]
参考 源码中的地址：String OFFICIAL_CONVERSATION_URL = "https://chat.openai.com/backend-api/conversation";以及OfficialBuilder.java的内容，发送post接口返回403,

另外，log日志中打印：ChatGPT Request: url=https://api.openai.com/v1/completions, data:{"model":"text-davinci-003","prompt":"","temperature":0.7,"max_tokens":3000,"stream":false,"top_p":1,"frequency_penalty":0,"presence_penalty":0}
这个与源码似乎不一致

**Comment by obiscr** [comment]
感谢提醒，这个是因为主分支的源码目前不是最新的，main分支还保留在chatgpt的模式，我会尽快把最新的源码上传。

**Comment by yhuso** [comment]
期待作者更新源码，学习研究~
