### ISSUE TITLE
AndroidStudio 2022.2.1 设置了jcef,还是无法使用

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [obiscr/ChatGPT#74]
![图片](https://user-images.githubusercontent.com/62411322/221086001-968105b4-b1a3-4a37-a3a0-99c8ddbd02ad.png)
![图片](https://user-images.githubusercontent.com/62411322/221086090-63088b16-8365-4881-8302-d40de9fabfb8.png)
![图片](https://user-images.githubusercontent.com/62411322/221086254-fe825e36-934f-4d67-ba9b-aa1388ce3af2.png)

**Comment by obiscr** [comment]
您好，请问是按照 [插件在Android Studio中无法使用？](https://chatgpt.cn.obiscr.com/faq/) 这里设置的吗？
或者您设置完成了以后，是否进行了重启 IDE操作呢？

**Comment by XiaoRanLiu3119** [comment]
> 您好，请问是按照 [插件在Android Studio中无法使用？](https://chatgpt.cn.obiscr.com/faq/) 这里设置的吗？ 或者您设置完成了以后，是否进行了重启 IDE操作呢？

是的,browser.jcef.enabled已打开
![图片](https://user-images.githubusercontent.com/62411322/221103462-3fdf6a5b-f3bd-49f8-956e-ae9815bd54c0.png)

并且下载并设置了包含JCEF的Runtime
![图片](https://user-images.githubusercontent.com/62411322/221103435-ce718746-b581-4dd5-bd88-c9312f7f36c7.png)
重启后 插件页还是显示nothing to show
我用的ide版本是Flamingo 2022.2.1的beta版,不知是否和这个有关

**Comment by obiscr** [comment]
有可能，能否尝试一下较低的版本

**Comment by XiaoRanLiu3119** [comment]
> 有可能，能否尝试一下较低的版本

谢谢,此版本这个配置正常使用,最新的正式版没安装就没试,不知后续是否会做兼容?
![图片](https://user-images.githubusercontent.com/62411322/221106532-f03fd705-c623-43e7-8dfd-e457a93887da.png)
![图片](https://user-images.githubusercontent.com/62411322/221106914-2c750b12-6ad7-4d87-8983-7141b5dde42d.png)

**Comment by obiscr** [comment]
> 式版没安装就没试,不知后续是



> > 有可能，能否尝试一下较低的版本
> 
> 谢谢,此版本这个配置正常使用,最新的正式版没安装就没试,不知后续是否会做兼容? ![图片](https://user-images.githubusercontent.com/62411322/221106532-f03fd705-c623-43e7-8dfd-e457a93887da.png) ![图片](https://user-images.githubusercontent.com/62411322/221106914-2c750b12-6ad7-4d87-8983-7141b5dde42d.png)

应该是因为你bata版本的缘故。后面视监控与了我会尽量支持的。
