### ISSUE TITLE
Support to configure cloudflare proxy

### ISSUE THREAD

**Issue by gclm** [obiscr/ChatGPT#8]
At present, it is not supported in China. I hope you can act as an agent, so that you can cf the network to make the plugin work properly.

## references

- https://github.com/cmdhelp/cloudflare-chatgpt

**Comment by obiscr** [comment]
Thanks. Yes, this feature is important. I will add it to the project as soon as possible.

**Comment by obiscr** [comment]
Now that v1.0.2 has been released, domestic sources can be switched. This way no token is needed.

**Comment by obiscr** [comment]
@gclm I'm not very familiar with cloudflare. Can you help me?

**Comment by gclm** [comment]
> @gclm I'm not very familiar with cloudflare. Can you help me?

OK，没问题。你想我如何协助你呢？

**Comment by gclm** [comment]
目前我自行编译报错，如果你需要我测试我个人建议你打个快照包放到github releases 里面，我测试完毕后再发正式版？
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/27618687/206857952-f29412aa-b2fe-444e-957b-41df424fd663.png">

**Comment by obiscr** [comment]
我已经配置好了，但是遇到了另外一个就是，我在浏览器 ，还有 postman访问 访问 cloudflaer 都是没问题的。但是在Java里面一直有问题，Connection time out，连接超时

**Comment by obiscr** [comment]
@gclm 这方面有什么经验嘛

**Comment by gclm** [comment]
- 目前你是在国内吗？你是不是一般都开着代理呢？
- 如果是的话那是正常的，目前cf自带的域名国内屏蔽了，你的代理postman 和 浏览器之所以能用是因为他们自动代理，但是Java程序无法自动代理。
- 解决办法： cf绑定个域名就可以了。

**Comment by obiscr** [comment]
好的，感谢，我尝试一下子

**Comment by gclm** [comment]
目前github消息提醒，感觉不太及时，我看见不及时，不好意思。

**Comment by obiscr** [comment]
我们加个微信吧：wx_wudaozi
