### ISSUE TITLE
How do I get a valid access token

### ISSUE THREAD

**Issue by sunupo** [obiscr/ChatGPT#9]
When I opened the site [https://chat.openai.com/api/auth/session](https://chat.openai.com/api/auth/session), there was no token displayed, just an empty json

**Comment by sunupo** [comment]
> When I opened the site https://chat.openai.com/api/auth/session, there was no token displayed, just an empty json

![image](https://user-images.githubusercontent.com/46593298/206838310-093c51bc-8059-4b49-9f7f-353944ad3ef3.png)

**Comment by sunupo** [comment]
About an hour later, the site returned a valid access token. ღ( ´･ᴗ･` )

**Comment by obiscr** [comment]
It's need to Log in.
